"""Initial migration

Revision ID: 46a7552e7ebb
Revises: 
Create Date: 2025-08-02 00:23:16.676458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46a7552e7ebb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('xp', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('level', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('streak_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_test_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('achievements', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('preferences', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('preferences')
        batch_op.drop_column('achievements')
        batch_op.drop_column('last_test_date')
        batch_op.drop_column('streak_days')
        batch_op.drop_column('level')
        batch_op.drop_column('xp')

    # ### end Alembic commands ###
