"""Add scientific IQ fields

Revision ID: 7ce01fcf5b4d
Revises: 1162b5dd178e
Create Date: 2025-08-04 00:47:35.642665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ce01fcf5b4d'
down_revision = '1162b5dd178e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fsiq', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('percentile', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('classification', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('domain_scores', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('confidence_interval', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('reliability_coefficient', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_session', schema=None) as batch_op:
        batch_op.drop_column('reliability_coefficient')
        batch_op.drop_column('confidence_interval')
        batch_op.drop_column('domain_scores')
        batch_op.drop_column('classification')
        batch_op.drop_column('percentile')
        batch_op.drop_column('fsiq')

    # ### end Alembic commands ###
